matrix:
  include:
    - env: TEST_SUITE=distribution
      sudo: required
      services:
        - docker
      language: bash
      before_install:
        - |
          # Always run on custom branches in main project as diff does not work.
          if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then
            echo "Checking to see if skippable..."
            if ! git diff --name-only "$TRAVIS_COMMIT_RANGE" | grep -qE '^(\.travis.yml|dist\/.*)$' ; then
              echo "No distribution related changes, stopping build process."
              exit
            fi
          fi
        - docker build -f dist/ci/Dockerfile -t spec .
      script:
        - docker run --rm -it spec ./dist/ci/spec.sh
    - env: TEST_SUITE=nosetests
      sudo: false
      language: python
      python: 2.7
      install:
        # needed to install osc from git in requirements.txt
        - pip install pycurl urlgrabber
        - pip install -r requirements.txt
        - pip install python-coveralls
      script:
        - nosetests --with-coverage --cover-package=osclib --cover-inclusive
      after_success:
        - coveralls
